//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCommerce.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComprobanteDelivery : Comprobante
    {
        public TipoPedido TipoPedido { get; set; }
        public EstadoPedido EstadoPedido { get; set; }
        public long DireccionId { get; set; }
        public Nullable<long> CadeteId { get; set; }
    
        public virtual Direccion Direccion { get; set; }
        public virtual Empleado Cadete { get; set; }
    }
}
