//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCommerce.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuracion
    {
        public long Id { get; set; }
        public Nullable<long> ListaDeliveryId { get; set; }
        public Nullable<long> ListaKioscoId { get; set; }
        public Nullable<long> MozoId { get; set; }
        public Nullable<long> CadeteId { get; set; }
    
        public virtual ListaPrecio ListaPrecioDelivery { get; set; }
        public virtual ListaPrecio ListaPrecioKiosco { get; set; }
        public virtual Categoria CategoriaMozo { get; set; }
        public virtual Categoria CategoriaCadete { get; set; }
    }
}
