//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCommerce.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operacion
    {
        public long Id { get; set; }
        public long CuentaCorrienteId { get; set; }
        public TipoOperacion TipoOperacion { get; set; }
        public decimal Monto { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal SubSaldo { get; set; }
    
        public virtual CuentaCorriente CuentaCorriente { get; set; }
        public virtual Comprobante Comprobante { get; set; }
    }
}
